### ISSUE TITLE
circleci学习

### ISSUE THREAD

**Issue by vnues** [vnues/blog#22]
## 概念

Your CircleCI configuration can be adapted to fit many different needs of your project. The following terms, sorted in order of granularity and dependence, describe the components of most common CircleCI projects:

- Pipeline: Represents the entirety of your configuration. Available in CircleCI Cloud only.
- Workflows: Responsible for orchestrating multiple jobs.
- Jobs: Responsible for running a series of steps that perform commands.
- Steps: Run commands (such as installing dependencies or running tests) and shell scripts to do the work required for your project.

Workflows工作流是组织一系列Jobs（用于编排所有 job），规定哪些分支可以触发哪些jobs

![image](https://user-images.githubusercontent.com/44258525/142234097-27a95a2d-00e0-4cc5-90aa-1777c04e78e7.png)

Jobs包含steps 具体执行哪些步骤

![image](https://user-images.githubusercontent.com/44258525/142235908-dd817240-ba6c-441e-b024-7f17299f7b4a.png)

![image](https://user-images.githubusercontent.com/44258525/142236172-b382035a-6d78-4a5d-99d5-92fbd9bd0f14.png)

## org

> org config组件化 2.1版本才有

![image](https://user-images.githubusercontent.com/44258525/142235566-2fb9f912-766f-4ab7-8827-6cc21989b108.png)

## config参考
- only ignore 进行筛选
```yaml
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints: 'b9:ef:45:6e:fc:1b:03:f8:3c:56:48:d0:d7:59:fe:ea'
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: ls -al
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npm run build
      - run: ls -al
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - dist
          key: dist
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - restore_cache:
  #         keys:
  #           - dist
  #           - v1-dependencies-{{ checksum "package.json" }}
  #           - v1-dependencies-
  #     - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
  #     - run: ls -al
  #     - run: # git config
  #         name: git-config
  #         command: |
  #           git config --global user.email "1518190293@qq.com"
  #           git config --global user.name "vnues"
  #     - run: npm run release
  #     - run:
  #         name: Add github.com to known hosts
  #         command: |
  #           mkdir -p ~/.ssh
  #           ssh-keyscan github.com >> ~/.ssh/known_hosts
  #     - run: # git push
  #         name: push-github
  #         command: |
  #           git checkout develop
  #           git rebase master
  #           git push
  #           git push --tags
  #     - run: npm publish

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: 
                /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: 
                /.*/
          branches:
              only:
                master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore:
                /.*/
```

## 参考资料

- [官方文档](https://circleci.com/docs/2.0/orb-author-intro/?section=configuration)
- [官方配置说明](https://circleci.com/docs/2.0/configuration-reference/)
- [使用 CircleCI 2.0 进行持续集成/持续部署
](https://www.jianshu.com/p/36af6af74dfc)
- [利用CircleCI自动发布npm包](https://blog.webbootcamp.cn/blogs/devops/circleci-npm-publish.html)
